# Generated by Django 4.0.4 on 2022-04-15 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_like_news_liked_users_like_news_like_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'db_table': 'Thumbnails',
            },
        ),
    ]
