# Generated by Django 4.0.4 on 2022-04-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_thumbnails'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thumbnails',
            table='thumbnails',
        ),
    ]
