# Generated by Django 4.0.4 on 2022-04-15 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='definion',
            new_name='definition',
        ),
    ]
