# Generated by Django 4.0.4 on 2022-04-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_news_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_writer',
        ),
    ]
