# Generated by Django 4.0.4 on 2022-04-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_news_news_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnails',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
