# Generated by Django 4.0.4 on 2022-04-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('word', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'word_count',
            },
        ),
    ]
