# Generated by Django 4.0.4 on 2022-04-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_nickname', models.CharField(max_length=20, unique=True)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=300)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
