# Generated by Django 4.0.4 on 2022-04-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_introduce',
            field=models.CharField(default='', max_length=300),
        ),
    ]
